// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2AbYIAATI1tz1zQG6b8LdwDCr40lCJ0',
    appId: '1:820658108421:web:e40042329a2381922cc46c',
    messagingSenderId: '820658108421',
    projectId: 'practice-c2ff9',
    authDomain: 'practice-c2ff9.firebaseapp.com',
    storageBucket: 'practice-c2ff9.appspot.com',
    measurementId: 'G-YSSLKW9MMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1YiV76RGqB0iVhp11rUEQ6rBAGsv-fM',
    appId: '1:820658108421:android:74dd482cff23b36b2cc46c',
    messagingSenderId: '820658108421',
    projectId: 'practice-c2ff9',
    storageBucket: 'practice-c2ff9.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-dydONFaIxGTWYMvg9LDb8lUvWEyTGEo',
    appId: '1:820658108421:ios:d36d7565c8bc2ab62cc46c',
    messagingSenderId: '820658108421',
    projectId: 'practice-c2ff9',
    storageBucket: 'practice-c2ff9.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-dydONFaIxGTWYMvg9LDb8lUvWEyTGEo',
    appId: '1:820658108421:ios:d36d7565c8bc2ab62cc46c',
    messagingSenderId: '820658108421',
    projectId: 'practice-c2ff9',
    storageBucket: 'practice-c2ff9.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2AbYIAATI1tz1zQG6b8LdwDCr40lCJ0',
    appId: '1:820658108421:web:8dfbe4ac24634ab82cc46c',
    messagingSenderId: '820658108421',
    projectId: 'practice-c2ff9',
    authDomain: 'practice-c2ff9.firebaseapp.com',
    storageBucket: 'practice-c2ff9.appspot.com',
    measurementId: 'G-Y7Y0P13XFH',
  );

}